### ISSUE TITLE
Error creating servicegroups

### ISSUE THREAD

**Issue by FLiPp3r90** [T-Systems-MMS/ansible-collection-icinga-director#13]
While deploy servicegroups with icinga_servicegroup module, the first run of any servicegroup will finish with an error.

The example playbook:
```
- hosts: localhost
  collections:
    - t_systems_mms.icinga_director
  tasks:
    - name: create servicegroup
      icinga_servicegroup:
        state: present
        url: "{{ icinga_director_url }}"
        url_username: "{{ icinga_user }}"
        url_password: "{{ icinga_pass }}"
        object_name: foo-test-prx
        assign_filter: 'host.name="foo-test-prx*"'
```

Any play will abort with following error:
```
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "assign_filter": "host.name=\"foo-test-prx*\"", 
            "client_cert": null, 
            "client_key": null, 
            "display_name": null, 
            "force_basic_auth": false, 
            "object_name": "foo-test-prx", 
            "state": "present", 
            "url": "https://7008.domon-web.internal.mms-support.de", 
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "url_username": "fnu-domon-7008", 
            "use_proxy": true, 
            "validate_certs": true
        }
    }, 
    "msg": "bad return code while creating: "
```

As a woraroud, you can set ignore_errors=true in any play, nevertheless the object was created successfully.
