### ISSUE TITLE
Removing host from icinga directory

### ISSUE THREAD

**Issue by david-ungurean** [T-Systems-MMS/ansible-collection-icinga-director#197]
### Question

Hello,
Can you provide an example of removing a host from Icinga?

Thank you.

**Comment by rndmh3ro** [comment]
```
- name: delete a host in icinga
  t_systems_mms.icinga_director.icinga_host:
    state: absent
    url: "{{ icinga_url }}"
    url_username: "{{ icinga_user }}"
    url_password: "{{ icinga_pass }}"
    object_name: "foohost"
```
