### ISSUE TITLE
icinga_service_template throws "Trying to recreate icinga_service"

### ISSUE THREAD

**Issue by trickert76** [T-Systems-MMS/ansible-collection-icinga-director#208]
I'm using the latest release and retrieve an error, when I run icinga_service_template twice with the same data. I tried to use "append", but that has the same result.

```
- name: "Configure Service Templates"
  t_systems_mms.icinga_director.icinga_service_template:
    url: "{{ inventory.monitoring.endpoint }}"
    url_username: "{{ inventory.monitoring.username }}"
    url_password: "{{ inventory.monitoring.password }}"
    state: "present"
    object_name: "standard-service"
    check_interval: 60
    check_timeout: 60
    enable_active_checks: true
    enable_event_handler: true
    enable_notifications: true
    enable_passive_checks: true
    enable_perfdata: true
    max_check_attempts: 5
    retry_interval: 30
```

throws

```
bad return code while creating: 422. Error message: Trying to recreate icinga_service ("{"object_name":"standard-service"}")
```

The template doesnt exist in the normal icinga configuration. It was once added via your module. The second run creates that error. So this isnt idempotent at all. I also tried to deploy the module and rerun the playbook, but again.
