### ISSUE TITLE
Parameters for check execution at Service Apply level are ignored

### ISSUE THREAD

**Issue by AnBenn** [T-Systems-MMS/ansible-collection-icinga-director#65]
Would be nice to have all variables concerning check execution also for the service apply available. At the moment I see them only on service template.

As far as I see at least these should be included:

    check_interval: 
    check_period: 
    check_timeout: 
    enable_active_checks: 
    enable_event_handler: 
    enable_notifications: 
    enable_passive_checks: 
    enable_perfdata: 
    max_check_attempts: 
    retry_interval:

My issue at the moment:
The Variables 
- check_interval
- retry_interval
- max_check_attempts
in the task below are ignored.

```
- name: check_load
  include_role:
    name: ansible_icinga
    tasks_from: "icinga_service_apply"
  vars:
    icinga_service_applies:
      - service_apply_object:
          - "check_load"
        imports:
          - domon-agent-load
        assign_filter: 'host.vars.StandardMonitoredBy="Agent"&host.vars.HostOS="Linux"'
        check_interval: 5m
        retry_interval: 5m
        max_check_attempts: 4
        vars:
          load_cload1: "$host.vars.load_cload1$"
          load_cload5: "$host.vars.load_cload5$"
          load_cload15: "$host.vars.load_cload15$"
```
