### ISSUE TITLE
Append properties

### ISSUE THREAD

**Issue by dskachan** [T-Systems-MMS/ansible-collection-icinga-director#96]
It would be nice to have some flag, which would allow to append some properties to the object - not exchange the old object with a new one. That would allow changing configurations of a system using both - ansible and icingaweb2. 

for example, there is a host, which were added using ansible: 

```
object Host "foo" {
    import "base_host_t"
    import "icinga_agent_t"

    display_name = "foo.domain.com"
    address = "10.10.10.10"
    check_command = "hostalive"
    vars.distribution = "Centos"
    vars.distribution_version = "7"
}
```

in some time, users have changed the object - added import "http_host_t" and vars.http_ssl = true

now, if the playbook will be played again - the object will be overwritten, and the variables will disappear. 

My proposal would be to add a flag, e.g. append,  to the object, like this: 

```
- name: make foo host in icinga
  t_systems_mms.icinga_director.icinga_host:
    state: present
    append: True
    url: "http://{{icinga_master}}/icingaweb2/"
    url_username: "{{icinga_api_user}}"
    url_password: "{{icinga_api_password}}"
    disabled: false
    object_name: foo
    address: 10.10.10.10
    display_name: "foo.domain.com"
    imports: "{{templates_include}}"
    vars: "{{icinga_host_vars}}"
    check_command: hostalive
```

So, I will be sure, that if I will play it again I will not delete any properties - only add if I have new ones. 
And, if I would want to overwrite my properties - I will set append to False, and I will be sure, that Icinga2 config will have exactly what I have in my ansible configs. 

I've done that once using REST API of the director, I believe that should be doable. I had an issue that time only with apply rules.
